# Generated by Django 6.0.8 on 2026-08-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinite_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(default='#4F46E5', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_numeric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='amount_done',
            field=models.IntegerField(default=0),
        ),
    ]
