# Generated by Django 6.0.8 on 2026-08-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinite_tracker', '0002_habit_category_habit_color_habit_is_numeric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
